In [75]:
import sys
import os
sys.path.insert(0, '/home/pvardanis/sms-tools/assignments/A1/A1_2017/A1')



In [60]:
%reload_ext autoreload
%autoreload 2


In [74]:
import numpy as np
import A1Part1
import A1Part2
import A1Part3
import A1Part4

In [62]:
A1Part1.readAudio('../../sounds/piano.wav')

array([-0.06213569, -0.04541154, -0.02734458, -0.0093997 ,  0.00769066,
        0.02319407,  0.03503525,  0.04309214,  0.04626606,  0.0441908 ],
      dtype=float32)

In [66]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
A1Part3.hopSamples(x,2)

array([0, 2, 4, 6, 8])

In [87]:
A1Part4.downsampleAudio('../../sounds/vibraphone-C6.wav',16)

In [95]:
!play '../../sounds/vibraphone-C6.wav'

play WARN alsa: can't encode 0-bit Unknown or not applicable

../../sounds/vibraphone-C6.wav:

 File Size: 287k      Bit Rate: 706k
  Encoding: Signed PCM    
  Channels: 1 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:03.25  

In:100%  00:00:03.25 [00:00:00.00] Out:143k  [      |      ]        Clip:0    
Done.


In [96]:
!play '../../workspace/A1/vibraphone-C6_downsampled.wav' 


play WARN alsa: can't encode 0-bit Unknown or not applicable

../../workspace/A1/vibraphone-C6_downsampled.wav:

 File Size: 18.0k     Bit Rate: 44.2k
  Encoding: Signed PCM    
  Channels: 1 @ 16-bit   
Samplerate: 2756Hz       
Replaygain: off         
  Duration: 00:00:03.25  

In:100%  00:00:03.25 [00:00:00.00] Out:8.96k [ -====|====- ]        Clip:0    
Done.
